### ISSUE TITLE
todo-list of open things

### ISSUE THREAD

**Issue by bbrehm** [joernio/flatgraph#21]
In no specific order:
- [ ] Traversal functionality for Iterator (path-tracking, where, and, or, repeat)
- [x] propertyDict for generated nodes
- [x] batchupdate integration for generated nodes 
- [ ] negated filter traversals for generated nodes
- [x] node starters
- [ ] indexing for node starters
- [ ] neighbor traversals for generated nodes
